opam-version: "2.0"
maintainer: "Jane Street developers"
authors: ["Jane Street Group, LLC"]
homepage: "https://github.com/janestreet/fixed_list"
bug-reports: "https://github.com/janestreet/fixed_list/issues"
dev-repo: "git+https://github.com/janestreet/fixed_list.git"
doc: "https://ocaml.janestreet.com/ocaml-core/latest/doc/fixed_list/index.html"
license: "MIT"
x-maintenance-intent: ["(latest)"]
build: [
  ["dune" "build" "-p" name "-j" jobs]
]
depends: [
  "ocaml" {>= "5.1.0"}
  "core"
  "ppx_jane"
  "dune"     {>= "3.17.0"}
]
available: arch != "x86_32"
synopsis: "Lists whose length is tracked in the OCaml type system"
description: "
`Fixed_list` provides lists whose length is tracked in the OCaml type system. This lets APIs express and preserve length relationships statically: for example, `map2` and `zip` only accept lists of the same length, and mapping over a fixed list returns a fixed list of the same length.
"
